MergingEnabled: No
MaxModelsAfterMerge: 1
MergeMinTranslationDist: 0.05
MergeMinHeadingDist: 0.01
ProcessNoisePositionFactor: 0.0100
ProcessNoiseHeadingFactor: 0.000100
ProcessNoiseVelocityFactor: 0.0100
ObservationDifferenceBearingFactor: 1
ObservationDifferenceElevationFactor: 0
