MergingEnabled: No
MaxModelsAfterMerge: 1
MergeMinTranslationDist: 0.05
MergeMinHeadingDist: 0.01
ProcessNoisePositionFactor: 0.1
ProcessNoiseHeadingFactor: 0.001
ProcessNoiseVelocityFactor: 0.1
ObservationDifferenceBearingFactor: 1
ObservationDifferenceElevationFactor: 0

