- duration: 700
  targets:
    - id: R_SHOULDER_PITCH
      position: 3.13955
      gain: 30
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 3.13955
      gain: 30
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.066473
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.066473
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -2.6589
      gain: 30
      torque: 100
    - id: L_ELBOW
      position: -2.6589
      gain: 30
      torque: 100
    - id: R_HIP_YAW
      position: -0.020453
      gain: 50
      torque: 100
    - id: L_HIP_YAW
      position: 0.020453
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: 0
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: 0
      gain: 50
      torque: 100
    - id: R_HIP_PITCH
      position: -0.271003
      gain: 50
      torque: 100
    - id: L_HIP_PITCH
      position: -0.271003
      gain: 50
      torque: 100
    - id: R_KNEE
      position: 0.424401
      gain: 50
      torque: 100
    - id: L_KNEE
      position: 0.424401
      gain: 50
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.05333
      gain: 50
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.05333
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.01534
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.01534
      gain: 50
      torque: 100
- targets:
    - id: R_SHOULDER_PITCH
      position: 0.772104
      gain: 30
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 0.772104
      gain: 30
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.158511
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.158511
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -2.71003
      gain: 30
      torque: 100
    - id: L_ELBOW
      position: -2.71003
      gain: 30
      torque: 100
    - id: R_HIP_YAW
      position: -0.025566
      gain: 50
      torque: 100
    - id: L_HIP_YAW
      position: 0.025566
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: 0.01534
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: -0.01534
      gain: 50
      torque: 100
    - id: R_HIP_PITCH
      position: -1.64647
      gain: 50
      torque: 100
    - id: L_HIP_PITCH
      position: -1.64647
      gain: 50
      torque: 100
    - id: R_KNEE
      position: 1.03288
      gain: 50
      torque: 100
    - id: L_KNEE
      position: 1.03288
      gain: 50
      torque: 100
    - id: R_ANKLE_PITCH
      position: -1.36524
      gain: 50
      torque: 100
    - id: L_ANKLE_PITCH
      position: -1.36524
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.046019
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.046019
      gain: 50
      torque: 100
  duration: 500
- duration: 1000
  targets:
    - id: R_SHOULDER_ROLL
      position: 0.035793
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: -0.035793
      gain: 30
      torque: 100
    - id: R_ELBOW
      position: -0.25055
      gain: 80
      torque: 100
    - id: L_ELBOW
      position: -0.25055
      gain: 80
      torque: 100
    - id: R_HIP_YAW
      position: 0.025566
      gain: 50
      torque: 100
    - id: L_HIP_YAW
      position: -0.025566
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: -0.025566
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: 0.025566
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.03068
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.03068
      gain: 50
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: -0.5124747
      gain: 10
      torque: 100
    - id: L_ANKLE_PITCH
      position: -0.6812538
      gain: 80
      torque: 100
    - id: R_ANKLE_PITCH
      position: -0.7763838
      gain: 80
      torque: 100
    - id: L_KNEE
      position: 1.01114
      gain: 80
      torque: 100
    - id: R_KNEE
      position: 1.067911
      gain: 80
      torque: 100
    - id: L_HIP_PITCH
      position: -1.925616
      gain: 80
      torque: 100
    - id: R_HIP_PITCH
      position: -1.848898
      gain: 80
      torque: 100
    - id: L_SHOULDER_PITCH
      position: -0.1077885
      gain: 80
      torque: 100
    - id: R_SHOULDER_PITCH
      position: -0.03720812
      gain: 80
      torque: 100
- targets:
    - gain: 10
      id: R_ELBOW
      position: -0.25055
      torque: 100
    - id: L_ELBOW
      position: -0.25055
      gain: 10
      torque: 100
    - id: R_HIP_YAW
      position: 0.025566
      gain: 50
      torque: 100
    - id: L_HIP_YAW
      position: -0.025566
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: -0.025566
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: 0.025566
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.03068
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.03068
      gain: 50
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: -0.5124747
      gain: 10
      torque: 100
    - id: L_KNEE
      position: 0.1028018
      gain: 50
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.09186953
      gain: 10
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.04277015
      gain: 10
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 0.1392428
      gain: 10
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 0.1637924
      gain: 10
      torque: 100
    - id: R_KNEE
      position: 0.1626417
      gain: 50
      torque: 100
    - id: L_HIP_PITCH
      position: -1.937891
      gain: 50
      torque: 100
    - id: R_HIP_PITCH
      position: -1.954769
      gain: 50
      torque: 100
    - id: L_ANKLE_PITCH
      position: -0.01994662
      gain: 80
      torque: 100
    - id: R_ANKLE_PITCH
      position: -0.1135423
      gain: 80
      torque: 100
  duration: 500
- targets:
    - id: R_ELBOW
      position: -0.25055
      gain: 30
      torque: 100
    - id: L_ELBOW
      position: -0.25055
      gain: 30
      torque: 100
    - id: R_HIP_YAW
      position: 0.025566
      gain: 50
      torque: 100
    - id: L_HIP_YAW
      position: -0.025566
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: -0.025566
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: 0.025566
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.03068
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.03068
      gain: 50
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 30
      torque: 100
    - id: HEAD_PITCH
      position: -0.5124747
      gain: 30
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.2898014
      gain: 30
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.3235572
      gain: 30
      torque: 100
    - id: L_SHOULDER_PITCH
      position: -0.07096393
      gain: 30
      torque: 100
    - id: R_SHOULDER_PITCH
      position: -0.075567
      gain: 30
      torque: 100
    - id: R_HIP_PITCH
      position: -1.973181
      gain: 80
      torque: 100
    - id: L_HIP_PITCH
      position: -1.945563
      gain: 80
      torque: 100
    - id: R_KNEE
      position: -0.1672447
      gain: 80
      torque: 100
    - id: L_KNEE
      position: -0.1687791
      gain: 80
      torque: 100
    - id: R_ANKLE_PITCH
      position: 0.4971311
      gain: 80
      torque: 100
    - id: L_ANKLE_PITCH
      position: 0.4787189
      gain: 80
      torque: 100
  duration: 500
- targets:
    - id: R_ELBOW
      position: -0.25055
      gain: 10
      torque: 100
    - id: L_ELBOW
      position: -0.25055
      gain: 10
      torque: 100
    - id: R_HIP_YAW
      position: 0.025566
      gain: 50
      torque: 100
    - position: -0.025566
      id: L_HIP_YAW
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: -0.025566
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: 0.025566
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.03068
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.03068
      gain: 50
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: -0.5124747
      gain: 10
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.2898014
      gain: 10
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.3235572
      gain: 10
      torque: 100
    - id: R_KNEE
      position: -0.09513003
      gain: 50
      torque: 100
    - id: L_KNEE
      position: -0.07825212
      gain: 50
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 1.000016
      gain: 10
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 1.000016
      gain: 10
      torque: 100
    - id: R_HIP_PITCH
      position: -1.965509
      gain: 50
      torque: 100
    - id: L_HIP_PITCH
      position: -1.936357
      gain: 50
      torque: 100
    - id: R_ANKLE_PITCH
      position: 0.4986655
      gain: 50
      torque: 100
    - id: L_ANKLE_PITCH
      position: 0.4771845
      gain: 50
      torque: 100
  duration: 1000
- targets:
    - id: R_ELBOW
      position: -0.25055
      gain: 10
      torque: 100
    - id: L_ELBOW
      position: -0.25055
      gain: 10
      torque: 100
    - id: R_HIP_YAW
      position: 0.025566
      gain: 50
      torque: 100
    - id: L_HIP_YAW
      position: -0.025566
      gain: 50
      torque: 100
    - id: R_HIP_ROLL
      position: -0.025566
      gain: 50
      torque: 100
    - id: L_HIP_ROLL
      position: 0.025566
      gain: 50
      torque: 100
    - id: R_ANKLE_ROLL
      position: 0.03068
      gain: 50
      torque: 100
    - id: L_ANKLE_ROLL
      position: -0.03068
      gain: 50
      torque: 100
    - id: HEAD_YAW
      position: 0
      gain: 10
      torque: 100
    - id: HEAD_PITCH
      position: -0.5124747
      gain: 10
      torque: 100
    - id: L_SHOULDER_ROLL
      position: 0.2898014
      gain: 10
      torque: 100
    - id: R_SHOULDER_ROLL
      position: -0.3235572
      gain: 10
      torque: 100
    - id: L_SHOULDER_PITCH
      position: 1.000016
      gain: 10
      torque: 100
    - id: R_SHOULDER_PITCH
      position: 1.000016
      gain: 10
      torque: 100
    - id: L_ANKLE_PITCH
      position: -0.3068711
      gain: 50
      torque: 100
    - id: R_ANKLE_PITCH
      position: -0.2792527
      gain: 50
      torque: 100
    - id: L_KNEE
      position: 1.540493
      gain: 50
      torque: 100
    - id: R_KNEE
      position: 1.519012
      gain: 50
      torque: 100
    - id: L_HIP_PITCH
      position: -1.933288
      gain: 50
      torque: 100
    - id: R_HIP_PITCH
      position: -1.950166
      gain: 50
      torque: 100
  duration: 1000