- duration: 500
  targets:
    - id: R_SHOULDER_PITCH
      torque: 100
      position: 2.15269
      gain: 30
    - gain: 30
      torque: 100
      id: L_SHOULDER_PITCH
      position: 2.15269
    - torque: 100
      position: -0.199418
      gain: 30
      id: R_SHOULDER_ROLL
    - position: 0.199418
      id: L_SHOULDER_ROLL
      torque: 100
      gain: 30
    - torque: 100
      gain: 30
      id: R_ELBOW
      position: -0.802783
    - torque: 100
      position: -0.802783
      id: L_ELBOW
      gain: 30
    - id: R_HIP_YAW
      position: 0
      torque: 100
      gain: 30
    - torque: 100
      position: 0
      id: L_HIP_YAW
      gain: 30
    - gain: 30
      torque: 100
      position: 0
      id: R_HIP_ROLL
    - gain: 30
      position: 0
      id: L_HIP_ROLL
      torque: 100
    - id: R_HIP_PITCH
      torque: 100
      gain: 30
      position: -1.09424
    - torque: 100
      id: L_HIP_PITCH
      position: -1.08913
      gain: 30
    - position: 1.66181
      gain: 30
      torque: 100
      id: R_KNEE
    - torque: 100
      id: L_KNEE
      position: 1.69249
      gain: 30
    - id: R_ANKLE_PITCH
      torque: 100
      position: -0.792557
      gain: 30
    - position: -0.736311
      torque: 100
      id: L_ANKLE_PITCH
      gain: 30
    - gain: 30
      position: 0.092039
      torque: 100
      id: R_ANKLE_ROLL
    - position: 0.097152
      gain: 30
      id: L_ANKLE_ROLL
      torque: 100
    - torque: 100
      id: HEAD_YAW
      position: 0
      gain: 10
    - gain: 10
      position: 0.9697126
      torque: 100
      id: HEAD_PITCH
- targets:
    - gain: 30
      torque: 100
      position: 3.79916
      id: R_SHOULDER_PITCH
    - torque: 100
      position: 3.79916
      id: L_SHOULDER_PITCH
      gain: 30
    - gain: 30
      position: -0.005113
      id: R_SHOULDER_ROLL
      torque: 100
    - gain: 30
      id: L_SHOULDER_ROLL
      torque: 100
      position: 0.005113
    - id: R_ELBOW
      position: -2.57197
      gain: 30
      torque: 100
    - position: -2.57197
      gain: 30
      torque: 100
      id: L_ELBOW
    - gain: 30
      torque: 100
      id: R_HIP_YAW
      position: 0
    - torque: 100
      id: L_HIP_YAW
      gain: 30
      position: 0
    - id: R_HIP_ROLL
      position: 0
      gain: 30
      torque: 100
    - position: 0
      torque: 100
      id: L_HIP_ROLL
      gain: 30
    - position: -0.76699
      gain: 30
      torque: 100
      id: R_HIP_PITCH
    - position: -0.787443
      torque: 100
      id: L_HIP_PITCH
      gain: 30
    - position: 1.59534
      torque: 100
      gain: 30
      id: R_KNEE
    - torque: 100
      position: 1.61579
      id: L_KNEE
      gain: 30
    - torque: 100
      position: 0.455081
      gain: 30
      id: R_ANKLE_PITCH
    - id: L_ANKLE_PITCH
      position: 0.465308
      gain: 30
      torque: 100
    - id: R_ANKLE_ROLL
      torque: 100
      gain: 30
      position: 0.178964
    - id: L_ANKLE_ROLL
      position: 0.046019
      torque: 100
      gain: 30
  duration: 500
- targets:
    - gain: 30
      id: R_SHOULDER_PITCH
      position: 4.0855
      torque: 100
    - torque: 100
      gain: 30
      position: 4.0855
      id: L_SHOULDER_PITCH
    - gain: 30
      id: R_SHOULDER_ROLL
      position: -0.056246
      torque: 100
    - gain: 30
      position: 0.056246
      torque: 100
      id: L_SHOULDER_ROLL
    - torque: 100
      id: R_ELBOW
      position: -1.8101
      gain: 30
    - gain: 30
      position: -1.8101
      torque: 100
      id: L_ELBOW
    - torque: 100
      position: 0
      gain: 30
      id: R_HIP_YAW
    - torque: 100
      gain: 30
      position: 0
      id: L_HIP_YAW
    - torque: 100
      id: R_HIP_ROLL
      position: 0
      gain: 30
    - position: 0
      id: L_HIP_ROLL
      torque: 100
      gain: 30
    - id: R_HIP_PITCH
      torque: 100
      gain: 30
      position: -1.2323
    - id: L_HIP_PITCH
      position: -1.19651
      torque: 100
      gain: 30
    - position: 1.76919
      id: R_KNEE
      torque: 100
      gain: 30
    - gain: 30
      id: L_KNEE
      position: 1.77942
      torque: 100
    - position: 0.453722
      id: R_ANKLE_PITCH
      gain: 30
      torque: 100
    - gain: 30
      position: 0.457249
      id: L_ANKLE_PITCH
      torque: 100
    - id: R_ANKLE_ROLL
      position: -0.035793
      torque: 100
      gain: 30
    - gain: 30
      position: -0.010227
      torque: 100
      id: L_ANKLE_ROLL
  duration: 500
- duration: 500
  targets:
    - id: R_SHOULDER_PITCH
      position: 3.3901
      gain: 30
      torque: 100
    - gain: 30
      position: 3.3901
      id: L_SHOULDER_PITCH
      torque: 100
    - id: R_SHOULDER_ROLL
      gain: 30
      position: -0.01534
      torque: 100
    - id: L_SHOULDER_ROLL
      torque: 100
      position: 0.01534
      gain: 30
    - position: -0.480647
      torque: 100
      gain: 30
      id: R_ELBOW
    - gain: 30
      torque: 100
      position: -0.480647
      id: L_ELBOW
    - torque: 100
      gain: 50
      position: 0
      id: R_HIP_YAW
    - position: 0
      torque: 100
      id: L_HIP_YAW
      gain: 50
    - gain: 50
      position: 0
      torque: 100
      id: R_HIP_ROLL
    - gain: 50
      position: 0
      torque: 100
      id: L_HIP_ROLL
    - position: 0.046019
      id: R_HIP_PITCH
      torque: 100
      gain: 50
    - id: L_HIP_PITCH
      gain: 50
      torque: 100
      position: 0.143172
    - gain: 50
      id: R_KNEE
      position: 1.52887
      torque: 100
    - position: 1.4266
      gain: 50
      id: L_KNEE
      torque: 100
    - gain: 50
      id: R_ANKLE_PITCH
      torque: 100
      position: -0.291456
    - position: -0.29657
      id: L_ANKLE_PITCH
      torque: 100
      gain: 50
    - id: R_ANKLE_ROLL
      position: -0.025566
      gain: 50
      torque: 100
    - position: -0.102265
      id: L_ANKLE_ROLL
      torque: 100
      gain: 50
- targets:
    - torque: 100
      position: 2.689341
      gain: 30
      id: R_SHOULDER_PITCH
    - gain: 30
      position: 2.709288
      id: L_SHOULDER_PITCH
      torque: 100
    - gain: 30
      torque: 100
      position: -0.053511
      id: R_SHOULDER_ROLL
    - position: 0.056579
      id: L_SHOULDER_ROLL
      torque: 100
      gain: 30
    - torque: 100
      position: 0.04488
      gain: 30
      id: R_ELBOW
    - torque: 100
      gain: 30
      id: L_ELBOW
      position: 0.029536
    - torque: 100
      id: R_HIP_YAW
      gain: 60
      position: -0.018412
    - position: 0.023015
      torque: 100
      id: L_HIP_YAW
      gain: 60
    - position: -0.016878
      id: R_HIP_ROLL
      gain: 60
      torque: 100
    - torque: 100
      id: L_HIP_ROLL
      position: -0.026084
      gain: 60
    - torque: 100
      id: R_HIP_PITCH
      position: 0.291528
      gain: 60
    - id: L_HIP_PITCH
      torque: 100
      position: 0.291528
      gain: 60
    - torque: 100
      position: 1.92715
      gain: 60
      id: R_KNEE
    - id: L_KNEE
      torque: 100
      gain: 60
      position: 1.919479
    - torque: 100
      position: -1.232087
      gain: 60
      id: R_ANKLE_PITCH
    - torque: 100
      position: -1.219813
      id: L_ANKLE_PITCH
      gain: 60
    - torque: 100
      gain: 60
      position: -0.009206
      id: R_ANKLE_ROLL
    - torque: 100
      id: L_ANKLE_ROLL
      position: 0.023015
      gain: 60
  duration: 500
- duration: 600
  targets:
    - id: R_HIP_YAW
      position: 0
      gain: 60
      torque: 100
    - gain: 60
      torque: 100
      id: L_HIP_YAW
      position: 0
    - torque: 100
      position: 0
      id: R_HIP_ROLL
      gain: 60
    - torque: 100
      id: L_HIP_ROLL
      gain: 60
      position: 0
    - id: L_ANKLE_ROLL
      position: -0.071586
      gain: 60
      torque: 100
    - torque: 100
      gain: 80
      position: 0.5048029
      id: R_HIP_PITCH
    - torque: 100
      id: L_HIP_PITCH
      position: 0.5124747
      gain: 80
    - id: R_KNEE
      gain: 80
      position: 1.88112
      torque: 100
    - position: 1.871914
      id: L_KNEE
      torque: 100
      gain: 80
    - position: -1.716944
      id: R_ANKLE_PITCH
      gain: 80
      torque: 100
    - id: L_ANKLE_PITCH
      gain: 80
      position: -1.588058
      torque: 100
    - id: R_ANKLE_ROLL
      position: -0.01994662
      gain: 80
      torque: 100
    - torque: 100
      gain: 80
      position: 2.669395
      id: R_SHOULDER_PITCH
    - position: 2.618761
      id: L_SHOULDER_PITCH
      torque: 100
      gain: 80
    - gain: 80
      position: -0.1118161
      torque: 100
      id: R_SHOULDER_ROLL
    - torque: 100
      id: L_SHOULDER_ROLL
      position: 0.03356402
      gain: 80
    - id: R_ELBOW
      torque: 100
      gain: 80
      position: -0.3448464
    - torque: 100
      position: -0.2543194
      id: L_ELBOW
      gain: 80
- targets:
    - id: R_SHOULDER_PITCH
      gain: 30
      torque: 100
      position: 1.60557
    - id: L_SHOULDER_PITCH
      position: 1.60557
      torque: 100
      gain: 30
    - position: -0.138058
      id: R_SHOULDER_ROLL
      torque: 100
      gain: 30
    - gain: 30
      torque: 100
      position: 0.138058
      id: L_SHOULDER_ROLL
    - gain: 30
      torque: 100
      position: -0.639159
      id: R_ELBOW
    - id: L_ELBOW
      gain: 30
      position: -0.639159
      torque: 100
    - position: 0
      torque: 100
      id: R_HIP_YAW
      gain: 60
    - torque: 100
      gain: 60
      id: L_HIP_YAW
      position: 0
    - id: R_HIP_ROLL
      position: 0
      gain: 60
      torque: 100
    - torque: 100
      position: 0
      gain: 60
      id: L_HIP_ROLL
    - id: R_HIP_PITCH
      position: -0.5011
      gain: 60
      torque: 100
    - id: L_HIP_PITCH
      gain: 60
      torque: 100
      position: -0.572686
    - position: 1.7
      id: R_KNEE
      gain: 60
      torque: 100
    - gain: 60
      id: L_KNEE
      torque: 100
      position: 1.7
    - id: R_ANKLE_PITCH
      gain: 60
      position: -1.00013
      torque: 100
    - gain: 60
      position: -1.00013
      id: L_ANKLE_PITCH
      torque: 100
    - gain: 60
      torque: 100
      position: 0.035793
      id: R_ANKLE_ROLL
    - position: -0.061359
      torque: 100
      gain: 60
      id: L_ANKLE_ROLL
  duration: 500
- targets:
    - torque: 100
      gain: 50
      id: R_HIP_YAW
      position: 0
    - torque: 100
      gain: 50
      id: L_HIP_YAW
      position: 0
    - id: R_HIP_ROLL
      position: -0.055
      torque: 100
      gain: 50
    - id: L_HIP_ROLL
      gain: 50
      position: 0.055
      torque: 100
    - position: -0.77
      gain: 50
      id: R_HIP_PITCH
      torque: 100
    - position: -0.77
      id: L_HIP_PITCH
      torque: 100
      gain: 50
    - position: 2.08
      torque: 100
      id: R_KNEE
      gain: 50
    - id: L_KNEE
      gain: 50
      torque: 100
      position: 2.08
    - torque: 100
      position: -1.31
      id: R_ANKLE_PITCH
      gain: 50
    - id: L_ANKLE_PITCH
      torque: 100
      position: -1.31
      gain: 50
    - position: 0.055
      gain: 50
      torque: 100
      id: R_ANKLE_ROLL
    - id: L_ANKLE_ROLL
      position: -0.055
      gain: 50
      torque: 100
    - id: L_ELBOW
      torque: 100
      gain: 20
      position: -2.5
    - position: 0.42
      torque: 100
      gain: 20
      id: L_SHOULDER_ROLL
    - position: 2.469929
      gain: 20
      id: L_SHOULDER_PITCH
      torque: 100
    - position: 2.47
      id: R_SHOULDER_PITCH
      gain: 20
      torque: 100
    - torque: 100
      position: -0.42
      gain: 20
      id: R_SHOULDER_ROLL
    - gain: 20
      position: -2.5
      id: R_ELBOW
      torque: 100
  duration: 500