gyroFactor: 0.18 * 0.273 * pi / 180 * 300 / 1024 # dps to rad/s conversion
ankleImuParamX: [0.5, 0.3 * 0.00025126605, 1 * pi / 180, 25 * pi / 180]
ankleImuParamY: [0.5, 1.2 * 0.00025126605, 1 * pi / 180, 25 * pi / 180]
kneeImuParamX: [0.5, 0.7 * 0.00025126605, 1 * pi / 180, 25 * pi / 180]
hipImuParamY: [0.5, 0.3 * 0.00025126605, 1 * pi / 180, 25 * pi / 180]
armImuParamX: [0.5, 10.0 * 0.00025126605, 20 * pi / 180, 45 * pi / 180]
armImuParamY: [0.5, 0.0 * 0.00025126605, 20 * pi / 180, 45 * pi / 180]

# These limit the distance a footstep will take
stanceLimitX: [-0.1, 0.1]
stanceLimitY: [0.07, 0.2]
stanceLimitAngle: [0, 0.5236]

# Velocity limits for the walk
velLimitX: [-0.03, 0.035]
velLimitY: [-0.03, 0.03]
velLimitA: [-0.4, 0.4]
# ??
velDelta: [0.02, 0.02, 0.15]
# Factor to slow down walk when turning
vaFactor: 0.6
# Ratio to normalize gyro gains into units of degree/second
velXHigh: 0.06
# ??
velDeltaXHigh: 0.01
footSizeX: [-0.05, 0.05]
# ??
stanceLimitMarginY: 0.015
# ??
stanceLimitY2: 0.02
# The body height of the robot, in meters; changing this will alter how high the robot's natural stance is.
bodyHeight: 0.285
# The angle of the torso when walking
bodyTilt: 0.4091
#
footX: 0
# The width of the robot's rest stance in meters.
footY: 0.035
# The distance the ankles rest behind the torso, in meters.
supportX: 0.02
# How far from the center of the foot the center of mass is placed during each step.
supportY: 0.01
hardnessSupport: 0.3
hardnessSwing: 0.3
hardnessArm: 0.3
# The tStep defines how long it will take for a robot to take its next step, in seconds.
tStep: 0.25
tZmp: 0.165
# The height to which the robot raises its foot at each step. This parameter is very sensitive in terms of balance.
stepHeight: 0.015
# The ratio of double support time: single support time (standing on two feet vs. balancing on one foot).
phaseSingle: [0.1, 0.9]
turnCompThreshold: 0
turnComp: 0

# Support bias parameters to reduce backlash-based instability
velFastForward: 0.05
velFastTurn: 0.15
supportFront: 0.03
supportFront2: 0.03
supportBack: -0.02
supportSideX: -0.01
supportSideY: -0.005
supportTurn: 0.02

frontComp: 0
accelComp: 0.1
supportModYInitial: 0
hipRollCompensation: 4 * pi / 180
toeTipCompensation: 0 * pi / 180
velCommandX: 0.035
velCommandY: 0
velCommandAngular: 0
balanceWeight: 0.7
STAND_SCRIPT_DURATION_MILLISECONDS: 1000
