stance:
  # The body height of the robot, in meters; changing this will alter how high the robot's natural stance is.
  body_height: 0.285
  # The angle of the torso when walking
  body_tilt: 25 * pi / 180
  # Default arm positions while walking
  arms:
    left:
      -   90 * pi / 180 # Shoulder Roll
      -   45 * pi / 180 # Shoulder Pitch
      - -140 * pi / 180 # Elbow
    right:
      -   90 * pi / 180 # Shoulder Roll
      -  -45 * pi / 180 # Shoulder Pitch
      - -140 * pi / 180 # Elbow
  foot_offset:
    - -0.02 # The distance the ankles are offset from the torso, in meters.
    - -0.01 # How far from the center of the foot the center of mass is placed during each step.
  # The gains to use for the servos during the walk
  gains:
    arms: 30
    legs: 30

walk_cycle:
  # Defines how long it will take for the robot to take its next step, in seconds.
  step_time: 0.25
  # ???
  zmp_time: 0.165
  step:
    # The height to which the robot raises its foot at each step. This parameter is very sensitive in terms of balance.
    height: 0.015
    # These limit the distance a footstep will take
    limits:
      - [-0.1, 0.1] # [min_x, max_x]
      - [0.07, 0.2] # [min_y, max_y]
      - [0, 30 * pi / 180] # [min_angle, max_angle]
  velocity:
    # Velocity limits for the walk
    limits:
      - [-0.03, 0.035] # [min_x, max_x]
      - [-0.03, 0.03] # [min_y, max_y]
      - [-0.4, 0.4] # [min_angle, max_angle]
    # This defines a 'fast' speed in the forward direction
    high_speed: 0.06
  acceleration:
    # Acceleration limits
    limits: [0.02, 0.02, 0.15]
    # When moving at 'fast' speed or faster, use these limits instead
    limits_high: [0.01, 0.02, 0.15]
    # Factor to slow down walk when turning
    turning_factor: 0.6
  # When to begin and end the single support phase. Range: [0,1]
  single_support_phase:
    start: 0.1
    end: 0.9


### TODO ###

# ??
stanceLimitMarginY: 0.015
# ??
turnCompThreshold: 0
# ??
turnComp: 0

# Support bias parameters to reduce backlash-based instability
velFastForward: 0.05
velFastTurn: 0.15
supportFront: 0.03
supportFront2: 0.03
supportBack: -0.02
supportSideX: -0.01
supportSideY: -0.005
supportTurn: 0.02

frontComp: 0
accelComp: 0.1
supportModYInitial: 0
hipRollCompensation: 4 * pi / 180
toeTipCompensation: 0 * pi / 180
balanceWeight: 0.7
STAND_SCRIPT_DURATION_MILLISECONDS: 1000

# Ratio to normalize gyro gains into units of degree/second
gyroFactor: 0.18 * 0.273 * pi / 180 * 300 / 1024 # dps to rad/s conversion
ankleImuParamX: [0.5, 0.3 * 0.00025126605, 1 * pi / 180, 25 * pi / 180]
ankleImuParamY: [0.5, 1.2 * 0.00025126605, 1 * pi / 180, 25 * pi / 180]
kneeImuParamX: [0.5, 0.7 * 0.00025126605, 1 * pi / 180, 25 * pi / 180]
hipImuParamY: [0.5, 0.3 * 0.00025126605, 1 * pi / 180, 25 * pi / 180]
armImuParamX: [0.5, 10.0 * 0.00025126605, 20 * pi / 180, 45 * pi / 180]
armImuParamY: [0.5, 0.0 * 0.00025126605, 20 * pi / 180, 45 * pi / 180]