ball_last_seen_max_time: 2
goal_last_seen_max_time: 4
start_position_offensive: [-0.2, 0]
start_position_defensive: [1.5, 0]
goalie: false

goalie_command_timeout: 1
goalie_rotation_speed_factor: 0.1
goalie_max_rotation_speed: 0.1
goalie_translation_speed_factor: 0.1
goalie_max_translation_speed: 0.1
goalie_side_walk_angle_threshold: 0.1