{
    #walk config
    "forwardSpeed" : 1.6, # 0.8,
    "footSeparation" : 0.140,
    "turnSpeed" : 1,

    #from robot model
    "footSize" : 0.10,

    #timers for starting turning and walking
    "walkStartTime" : 0.2,
    "walkTurnTime" : 0.2,

    #walk accel/deccel controls
    "accelerationTime" : 0.2,
    "accelerationFraction" : 0.5,

    #approach speeds
    "closeApproachSpeed" : 0.7, # 0.45,
    "closeApproachDistance" : 0.30,
    "midApproachSpeed" : 2.0, # 1.0,
    "midApproachDistance" : 0.60,

    #turning values
    "turnDeviation" : 0.1,

    #state controls
    #var approachDistance??

    #hystereses
    "distanceHysteresis" : 0.10,
    "turningHysteresis" : 0.1,
    "positionHysteresis" : 0.30,

    #ball lineup
    "ballLineupDistance" : 0.2,
    "ballLineupMinDistance" : 0.060,

    #extra config options
    "useAvoidance" : false,
    "assumedObstacleWidth" : 0.250,
    "avoidDistance" : 0.500,

    "bearingSensitivity" : 0.15,
    "ApproachCurveFactor" : 0.45
}
