#The proportional gain for the tracking updates
p_gain_tracking: 0.5
#The angular padding to place between an object and the edge of the screen
view_padding_radians: 0.1

#Debug:
debug_look_index: 0

lost_searchs:
  -low_first:
  	#enum type for search
    search_type: "LOW_FIRST"
    #Points in normalised view space. [1,1] corresponds to looking up to the right as far as allowed, relative to the body
    points:
      -[-1,-1]
      -[0,-1]
      -[1,-1]
      -[1,0]
      -[0,0]
      -[-1,0]
