kick_priority: 30
execution_priority: 40


target: [0.1, 0, 0.05] #in support foot coordinates for debugging
direction: [1, 0, 0]

servo:
  gain: 30
  torque: 100

balancer:
  foot_separation: 0.074 # 0.074 = hip separation
  adjustment: 0 #default value is 0. 
  stand_height: 0.22 #m 
  forward_lean: 0.0 #m
  
  forward_velocity: 0.1 #m/s
  return_velocity: 0.1 #m/s


lifter:
  lift_foot_height: 0.05 #m
  lift_foot_back: 0.01 #m
  forward_velocity: 0.1 #m/s
  return_velocity: 0.1 #m/s

kicker:
  forward_velocity: 0.5 #m/s
  return_velocity: 0.5 #m/s
