kick_priority: 30
execution_priority: 40

target: [1, 1, 1]
direction: [2, 2, 2]

balancer:
  motion_gain: 0.1
  stand_height: 0.18

lifter:
  motion_gain: 0.1
  lift_foot_height: 0.05
  lift_foot_back: 0.01

kicker:
  motion_gain: 0.1