kick_priority: 30
execution_priority: 40


target: [0.1, 0, 0.05] #in support foot coordinates for debugging
direction: [1, 0, 0]

servo:
  gain: 30
  torque: 100

balancer:
  foot_separation: 0.074 # 0.074 = hip separation
  adjustment: 0.00 #default value is 0.
  stand_height: 0.22 #m
  forward_lean: 0.0 #m

  forward_velocity: 0.05 #m/s
  return_velocity: 0.05 #m/s


lifter:
  lift_foot_height: 0.05 #m
  put_foot_down_height: 0.045 #m #default value is lift_foot_height
  lift_foot_back: 0.01 #m
  forward_velocity: 0.05 #m/s
  return_velocity: 0.1 #m/s

kicker:
  forward_velocity: 0.1 #m/s
  return_velocity: 0.05 #m/s

active_balance:
  angle_gain:
    p: 0.5
    i: 0.0
    d: 0.0
  translation_gain:
    X:
      p: 0.0
      d: -0.0
    Y:
      p: 0
      d: 0
    Z:
      p: 0.035
      d: 0  
