kick_priority: 30
execution_priority: 40


target: [0.1, 0, 0.05] #in support foot coordinates for debugging
direction: [1, 0, 0]

balancer:
  foot_separation: 0.074 # 0.074 = hip separation
  motion_gain: 10 # gain per second
  stand_height: 0.22 #m 
  tolerance: 0.01 #m

lifter:
  # motion_gain: 0.1
  lift_foot_height: 0.05 #m
  lift_foot_back: 0.01 #m
  velocity: 0.05

kicker:
  # motion_gain: 0.1
  kick_velocity: 0.5
  return_velocity: 0.5
