output:
  file:
    enabled: true
    path: DataStream/
  network:
    enabled: true
    pub_port: 12000
    sub_port: 12001
    high_water_mark: 50
    max_image_fps: 10
    max_classified_image_fps: 10

# Select which data to send
reaction_handles:
  # Overview information for the dashboard, designed for minimum bandwidth
  overview: true
  # Motor positions, orientation, etc.
  sensor_data: false
  # Raw image
  image: false
  # Classified image
  classified_image: false
  # Vision objects including goals, balls and debugging lines
  vision_object: false
  # Localisation state estimates and uncertainties
  localisation: false
  # Data for chart tool in NUsight
  data_point: false
  # Field drawn objects such as an arrow, sphere, etc
  draw_objects: false
  # Subsumption data
  subsumption: false
  # GameController information
  game_state: false
  # Behaviour information
  behaviour: false
  # Statistics about reactions, modules and runtimes
  reaction_statistics: false

  #### things you probably wouldn't want to disable below ####

  # NUsight commands (download_lut, etc)
  command: false
  # Updates to enabled reaction handles
  reaction_handles: false
  # Ping packets
  ping: false
  # Configuration window
  configuration_state: false
  # Lookup table packets
  lookup_table: false
  # Lookup table delta packets (autoclassifier)
  lookup_table_diff: false
