output:
  file:
    enabled: true
    path: DataStream/
  network:
    enabled: true
    pub_port: 12000
    sub_port: 12001
    high_water_mark: 50
    max_image_fps: 10
    max_classified_image_fps: 10

# Select which data to send
reaction_handles:
  # Overview information for the dashboard, designed for minimum bandwidth
  overview: true
  # Ping packets
  ping: true
  # Motor positions, orientation, etc.
  sensor_data: true
  # Raw image
  image: true
  # Classified image
  classified_image: true
  # Vision objects including goals, balls and debugging lines
  vision_object: true
  # Localisation state estimates and uncertainties
  localisation: true
  # Data for chart tool in NUsight
  data_point: true
  # Field drawn objects such as an arrow, sphere, etc
  draw_objects: true
  # Lookup table packets
  lookup_table: true
  # Lookup table delta packets (autoclassifier)
  lookup_table_diff: true
  # Subsumption data
  subsumption: true
  # NUsight commands (download_lut, etc)
  command: true
  # Updates to enabled reaction handles
  reaction_handles: true
  # GameController information
  game_state: true
  # Configuration window
  configuration_state: true
  # Behaviour information
  behaviour: true
  # Statistics about reactions, modules and runtimes
  reaction_statistics: true
